In [1]:
import os
import numpy as np
import pandas as pd
from nltk.tokenize import word_tokenize

In [2]:
#Traversing the path and enlisting the folders and files
x = [os.path.join(r,file) for r,d,f in os.walk(r'''newsgroups''') for file in f]
print(len(x))
y = [os.path.join(r,direc) for r,d,f in os.walk(r'''newsgroups''') for direc in d]
print(y)


19997
['newsgroups\\alt.atheism', 'newsgroups\\comp.graphics', 'newsgroups\\comp.os.ms-windows.misc', 'newsgroups\\comp.sys.ibm.pc.hardware', 'newsgroups\\comp.sys.mac.hardware', 'newsgroups\\comp.windows.x', 'newsgroups\\misc.forsale', 'newsgroups\\rec.autos', 'newsgroups\\rec.motorcycles', 'newsgroups\\rec.sport.baseball', 'newsgroups\\rec.sport.hockey', 'newsgroups\\sci.crypt', 'newsgroups\\sci.electronics', 'newsgroups\\sci.med', 'newsgroups\\sci.space', 'newsgroups\\soc.religion.christian', 'newsgroups\\talk.politics.guns', 'newsgroups\\talk.politics.mideast', 'newsgroups\\talk.politics.misc', 'newsgroups\\talk.religion.misc']


In [3]:
#Spliting the files into Train and Test files
test_file = []
train_file = x
print(len(train_file))
for i in range(0,19996,50):
    test_file.append(x[i])
for file in test_file:
     train_file.remove(file)

19997


In [4]:
print(len(test_file))
print(len(train_file))

400
19597


In [5]:
#Making a complete list of stop words which also includes some special characters present in the texts of data
from stop_words import get_stop_words
stop_words = get_stop_words('english')
del stop_words[-1]
stop_words_i = [word.title() for word in stop_words]
stop_words_u = [word.upper() for word in stop_words]
others = [str(i) for i in range(101)] + [str(i)+"." for i in range(101)]
sp = ["''",'""',"'",'"','!','~','`','!','@','#','$','%','^','&','*','/','-','+','_',':)','**','***','_/','----------------------------------------------------------------------','[]','{}','()','\\','|','[',']','(','|>','>>','<<',
')','{','}',',','.','?','=','<=','>=','<','>',':',';','A','B','Q','W','E','R','T','Y','U','I','O','P','S','D','F','G','H','J','K','L','Z','X','C','V','N','M','A.','B.','Q.','W.','E.','R.','T.','Y.','U.','I.','O.','P.','S.','D.','F.','G.','H.','J.','K.','L.','Z.','X.','C.','V.','N.','M.']
stop_words = stop_words + stop_words_i + stop_words_u + others + sp

In [6]:
#Building the vocabulary 
vocab = {}
for j in range(0,len(train_file)):
    text = word_tokenize(open(train_file[j]).read()) #Converting string words into tokens
    for k in text:
        if k not in stop_words:
            if vocab.get(k)!= None:
                vocab[k]+=1
            else:
                vocab[k]=1

In [7]:
voc = vocab
voc = sorted(voc.items(), key=lambda x: x[1], reverse=True) #Sorting the words according to their frequencies in the dataset
col = voc[0:2000] #Choosing top 2000 most occuring words
col = dict(col) 
columns = list(col.keys()) #list of all 2000 words

In [8]:
#creating 5 2-D arrays with every value 0
# getting the memory error if done in one single matrix thats why created 5
a1 = np.array([[0] * len(col) for _ in range(5000)])

In [9]:
a2 = np.array([[0] * len(col) for _ in range(5000)])

In [10]:
a3 = np.array([[0] * len(col) for _ in range(5000)])

In [11]:
a4 = np.array([[0] * len(col) for _ in range(4000)])

In [12]:
a4.shape

(4000, 2000)

In [13]:
len(columns)

2000

In [14]:
# Traversing the text files once again 
# Travering each word and marking its frequency if it one of the most occuring word
# Doing same for all 5 2D arrays
# Converting the arrays into dataframes

for j in range(0,5000):
    text = word_tokenize(open(train_file[j]).read())
    for k in text:
        if k in columns:
            pos = columns.index(k)
            a1[j][pos] += 1

In [15]:
d1= pd.DataFrame(data= a1, columns=columns)

In [16]:
for j in range(0,5000):
    text = word_tokenize(open(train_file[j+5000]).read())
    for k in text:
        if k in columns:
            pos = columns.index(k)
            a2[j][pos] += 1


In [17]:
d2= pd.DataFrame(data= a2, columns=columns)

In [18]:
for j in range(0,5000):
    text = word_tokenize(open(train_file[j+10000]).read())
    for k in text:
        if k in columns:
            pos = columns.index(k)
            a3[j][pos] += 1


In [19]:
d3= pd.DataFrame(data= a3, columns=columns)

In [20]:
for j in range(0,4000):
    text = word_tokenize(open(train_file[j+15000]).read())
    for k in text:
        if k in columns:
            pos = columns.index(k)
            a4[j][pos] += 1


In [21]:
d4= pd.DataFrame(data= a4, columns=columns)

In [22]:
a5 = np.array([[0] * len(col) for _ in range(597)])

for j in range(len(a5)):
    text = word_tokenize(open(train_file[j+19000]).read())
    for k in text:
        if k in columns:
            pos = columns.index(k)
            a5[j][pos] += 1

d5= pd.DataFrame(data= a5, columns=columns)

In [23]:
# Appending all 5 dataframes into 1
df = d1.append([d2,d3,d4,d5])

In [24]:
# Using dataframe as matrix once again
data = df.as_matrix()

In [25]:
# saving dataframe into a CSV file
df.to_csv("train_text.csv", sep = ',')

In [26]:
df.shape

(19597, 2000)

In [ ]:
# Making a names of the groups files belong to
t = []
for group in train_file:
    g = group.split('\\')[1]
    t.append(g)
t

In [28]:
#  Making a dictionary of groups to give them an integer value which shows class
#  I have classified 20 groups into 6 classes viz, Religion, Computer, Vehicles, Sports, Politics and for_sale
dic = {'alt.atheism':1,
 'comp.graphics':2,
 'comp.os.ms-windows.misc':2,
 'comp.sys.ibm.pc.hardware':2,
 'comp.sys.mac.hardware':2,
 'comp.windows.x':2,
 'misc.forsale':3,
 'rec.autos':4,
 'rec.motorcycles':4,
 'rec.sport.baseball':4,
 'rec.sport.hockey':4,
 'sci.crypt':5,
 'sci.electronics':5,
 'sci.med':5,
 'sci.space':5,
 'soc.religion.christian':1,
 'talk.politics.guns':6,
 'talk.politics.mideast':6,
 'talk.politics.misc':6,
 'talk.religion.misc':1}

In [29]:
# Maping from the dictionary the integer value to each group
target = []
for group in train_file:
    g = group.split('\\')[1]
    target.append(dic[g])

# Now we have 2 datasets one data which contains the frequencies of words
# second is target datasets containg the classes of texts

In [30]:
set(target)

{1, 2, 3, 4, 5, 6}

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [32]:
#Spliting the Train data 
Xtrain, Xtest, Ytrain, Ytest = train_test_split(data, target, random_state = 1, test_size=0.33)

In [33]:
clf = MultinomialNB()
clf.fit(Xtrain,Ytrain)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [34]:
clf.score(Xtest,Ytest)

0.82838589981447119

In [35]:
#Doing same procedure for Test_file also 
a_test = np.array([[0] * len(col) for _ in range(len(test_file))])

for j in range(len(a_test)):
    text = word_tokenize(open(test_file[j]).read())
    for k in text:
        if k in columns:
            pos = columns.index(k)
            a_test[j][pos] += 1
            
d_test= pd.DataFrame(a_test, columns=columns)

In [36]:
d_test.to_csv("test_text.csv", sep = ',')
data_test = d_test.as_matrix()

In [37]:
target_test = []
for group in test_file:
    g = group.split('\\')[1]
    target_test.append(dic[g])

In [38]:
clf.score(data_test, target_test)

0.79500000000000004

In [39]:
Ytrain_predict = clf.predict(Xtest)
Ytest_predict = clf.predict(data_test)

In [41]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(Ytest,Ytrain_predict))
print(confusion_matrix(Ytest,Ytrain_predict))

             precision    recall  f1-score   support

          1       0.94      0.86      0.90       942
          2       0.99      0.62      0.76      1650
          3       0.35      0.94      0.51       326
          4       0.89      0.95      0.92      1284
          5       0.82      0.88      0.85      1284
          6       0.90      0.88      0.89       982

avg / total       0.88      0.83      0.84      6468

[[ 813    0   13   26   10   80]
 [   4 1027  379   47  193    0]
 [   1    0  305   11    9    0]
 [   1    0   45 1221   13    4]
 [  10    9   90   40 1128    7]
 [  35    1   34   24   24  864]]


In [42]:
print(classification_report(target_test, Ytest_predict))
print(confusion_matrix(target_test, Ytest_predict))

             precision    recall  f1-score   support

          1       0.96      0.78      0.86        60
          2       0.97      0.59      0.73       100
          3       0.33      1.00      0.50        20
          4       0.89      0.93      0.91        80
          5       0.78      0.86      0.82        80
          6       0.83      0.82      0.82        60

avg / total       0.86      0.80      0.81       400

[[47  0  3  1  0  9]
 [ 1 59 23  3 14  0]
 [ 0  0 20  0  0  0]
 [ 0  0  4 74  1  1]
 [ 1  2  6  2 69  0]
 [ 0  0  4  3  4 49]]


In [44]:
tar = np.array(target)
np.savetxt('train_text_targets.csv', tar, header= 'classes')

In [45]:
tar = np.array(target_test)
np.savetxt('test_text_targets.csv', tar, header= 'classes')